name: Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint mypy black isort
        pip install -e .
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # full linting with specified configuration
        flake8 htucker/ examples/
    - name: Check formatting with black
      run: |
        black --check --diff htucker/ examples/
    - name: Check imports with isort
      run: |
        isort --check --diff htucker/ examples/
    - name: Type checking with mypy
      run: |
        mypy htucker/
